In [137]:
import pandas as pd
import numpy as np
data = pd.read_csv("ha.csv")
data.columns = ['age', 'sex', 'chest_pain_type', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar', 'rest_ecg', 'max_heart_rate_achieved',
       'exercise_induced_angina', 'st_depression', 'st_slope','target']
data.describe()

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,target
count,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000
mean,53.720168,0.763866,3.232773,132.153782,210.363866,0.213445,0.698319,139.732773,0.387395,0.922773,1.624370,0.528571
std,9.358203,0.424884,0.935480,18.368823,101.420489,0.409912,0.870359,25.517636,0.487360,1.086337,0.610459,0.499393
min,28.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,-2.600000,0.000000,0.000000
25%,47.000000,1.000000,3.000000,120.000000,188.000000,0.000000,0.000000,121.000000,0.000000,0.000000,1.000000,0.000000
50%,54.000000,1.000000,4.000000,130.000000,229.000000,0.000000,0.000000,140.500000,0.000000,0.600000,2.000000,1.000000
75%,60.000000,1.000000,4.000000,140.000000,269.750000,0.000000,2.000000,160.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,1.000000

In [138]:
'''q1 = data.resting_blood_pressure.quantile(0.25)
q2 = data.resting_blood_pressure.quantile(0.75)
print(q1,q2)
q3 = data.cholesterol.quantile(0.25)
q4 = data.cholesterol.quantile(0.75)
print(q3,q4)
q5 = data.max_heart_rate_achieved.quantile(0.25)
q6 = data.max_heart_rate_achieved.quantile(0.75)
print(q5,q6)
q7 = data.st_depression.quantile(0.25)
q8 = data.st_depression.quantile(0.75)
print(q7,q8)'''

'q1 = data.resting_blood_pressure.quantile(0.25)\nq2 = data.resting_blood_pressure.quantile(0.75)\nprint(q1,q2)\nq3 = data.cholesterol.quantile(0.25)\nq4 = data.cholesterol.quantile(0.75)\nprint(q3,q4)\nq5 = data.max_heart_rate_achieved.quantile(0.25)\nq6 = data.max_heart_rate_achieved.quantile(0.75)\nprint(q5,q6)\nq7 = data.st_depression.quantile(0.25)\nq8 = data.st_depression.quantile(0.75)\nprint(q7,q8)'

In [24]:
'''IQR = q2-q1
print(IQR)
IQR = q4-q3
print(IQR)
IQR = q6-q5
print(IQR)
IQR = q8-q7
print(IQR)'''

20.0
81.75
39.0
1.6

In [43]:
'''lower_limit = q1-1.5*IQR
upper_limit = q2+1.5*IQR
print(lower_limit,upper_limit)
lower_limit1 = q3-1.5*IQR
upper_limit1= q4+1.5*IQR
print(lower_limit1,upper_limit1)
lower_limit2 = q5-1.5*IQR
upper_limit2 = q6+1.5*IQR
print(lower_limit2,upper_limit2)
lower_limit3 = q7-1.5*IQR
upper_limit3 = q8+1.5*IQR
print(lower_limit3,upper_limit3)'''

#data[(data.st_depression>lower_limit3)&(data.st_depression<upper_limit3)]

90.0 170.0
158.0 299.75
91.0 190.0
-30.0 31.6

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,target
0,40,1,2,140,289,0,0,172,0,0.0,1,0
1,49,0,3,160,180,0,0,156,0,1.0,2,1
2,37,1,2,130,283,0,1,98,0,0.0,1,0
3,48,0,4,138,214,0,0,108,1,1.5,2,1
4,54,1,3,150,195,0,0,122,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,45,1,1,110,264,0,0,132,0,1.2,2,1
1186,68,1,4,144,193,1,0,141,0,3.4,2,1
1187,57,1,4,130,131,0,0,115,1,1.2,2,1
1188,57,0,2,130,236,0,2,174,0,0.0,2,1
1189,38,1,3,138,175,0,0,173,0,0.0,1,0

In [27]:
#data[(data.resting_blood_pressure<lower_limit)&(data.resting_blood_pressure>upper_limit)&(data.cholesterol<lower_limit1)&(data.cholesterol>upper_limit1)&(data.max_heart_rate_achieved<lower_limit2)&(data.max_heart_rate_achieved>upper_limit2)&(data.st_depression<lower_limit3)&(data.st_depression>upper_limit3)]

Empty DataFrame
Columns: [age, sex, chest_pain_type, resting_blood_pressure, cholesterol, fasting_blood_sugar, rest_ecg, max_heart_rate_achieved, exercise_induced_angina, st_depression, st_slope, target]
Index: []

In [148]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

q1 = data.resting_blood_pressure.quantile(0.25)
q2 = data.resting_blood_pressure.quantile(0.75)
print(q1,q2)
IQR = q2-q1
print(IQR)
lower_limit = q1-1.5*IQR
upper_limit = q2+1.5*IQR
print(lower_limit,upper_limit)

q3 = data.cholesterol.quantile(0.25)
q4 = data.cholesterol.quantile(0.75)
print(q3,q4)
IQR = q4-q3
print(IQR)
lower_limit1 = q3-1.5*IQR
upper_limit1= q4+1.5*IQR
print(lower_limit1,upper_limit1)

q5 = data.max_heart_rate_achieved.quantile(0.25)
q6 = data.max_heart_rate_achieved.quantile(0.75)
print(q5,q6)
IQR = q6-q5
print(IQR)
lower_limit2 = q5-1.5*IQR
upper_limit2 = q6+1.5*IQR
print(lower_limit2,upper_limit2)

df_no_outlier =data[(data.resting_blood_pressure>lower_limit)&(data.resting_blood_pressure<upper_limit)&(data.cholesterol>lower_limit1)&(data.cholesterol<upper_limit1)&(data.max_heart_rate_achieved>lower_limit2)&(data.max_heart_rate_achieved<upper_limit2)]
#df_no_outlier = data[(data.max_heart_rate_achieved>lower_limit2)&(data.max_heart_rate_achieved<upper_limit2)]
X = df_no_outlier.drop('target',axis=1)
y = df_no_outlier['target']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
from sklearn.linear_model import LogisticRegression
#LogReg_clf = LogisticRegression(random_state = 0)
#classifier.fit(X_train, y_train)
#y_pred = classifier.predict(X_test)
#accuracy = accuracy_score(y_test, y_pred)
#print("Accuracy: %.2f%%" % (accuracy * 100.0))
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
df_no_outlier

120.0 140.0
20.0
90.0 170.0
188.0 269.75
81.75
65.375 392.375
121.0 160.0
39.0
62.5 218.5
Accuracy: 93.72%

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,target
0,40,1,2,140,289,0,0,172,0,0.0,1,0
1,49,0,3,160,180,0,0,156,0,1.0,2,1
2,37,1,2,130,283,0,1,98,0,0.0,1,0
3,48,0,4,138,214,0,0,108,1,1.5,2,1
4,54,1,3,150,195,0,0,122,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,45,1,1,110,264,0,0,132,0,1.2,2,1
1186,68,1,4,144,193,1,0,141,0,3.4,2,1
1187,57,1,4,130,131,0,0,115,1,1.2,2,1
1188,57,0,2,130,236,0,2,174,0,0.0,2,1
1189,38,1,3,138,175,0,0,173,0,0.0,1,0

In [149]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, y_train)
from sklearn.metrics import accuracy_score
threshold =0.450958
predicted_proba = classifier.predict_proba(X_test)
pr = (predicted_proba [:,1] >= threshold).astype('int')
accuracy = accuracy_score(y_test, pr)
print(accuracy*100)

94.24083769633508

In [3]:
from yellowbrick.model_selection import validation_curve 
from sklearn.ensemble import RandomForestClassifier
train_scoreNum, test_scoreNum = validation_curve(RandomForestClassifier(),X = x_train, y = y_train, param_name = 'n_estimators', param_range = num_est, cv = 3)

NameError: name 'x_train' is not defined

In [151]:
pip install yellowbrick

Collecting yellowbrick
  Downloading yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
     |████████████████████████████████| 271 kB 2.7 MB/s eta 0:00:01
Requirement already satisfied: numpy<1.20,>=1.16.0 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from yellowbrick) (1.18.5)
Requirement already satisfied: scipy>=1.0.0 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from yellowbrick) (1.5.0)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from yellowbrick) (3.2.2)
Requirement already satisfied: scikit-learn>=0.20 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from yellowbrick) (0.24.2)
Requirement already satisfied: cycler>=0.10.0 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from yellowbrick) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.8.1)
Requirement already satisfied: joblib>=0.11 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from scikit-learn>=0.20->yellowbrick) (0.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/nisarga/anaconda3/lib/python3.8/site-packages (from scikit-learn>=0.20->yellowbrick) (2.1.0)
Requirement already satisfied: six in /home/nisarga/anaconda3/lib/python3.8/site-packages (from cycler>=0.10.0->yellowbrick) (1.15.0)
Installing collected packages: yellowbrick
Successfully installed yellowbrick-1.3.post1
Note: you may need to restart the kernel to use updated packages.